### ISSUE TITLE
SMS signup intro message and first question send at the same time

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#103]
The intro message and first question send at the same time despite trying to add a pause.

Related to issue https://github.com/twilio/twilio-ruby/issues/172

**Comment by shua123** [comment]
No great way to fix this at the moment. Possibly cut down intro message and first question so that they can fit in one message.

**Comment by smarziano** [comment]
Here are two new versions that combine the intro message and the first question. @shua123 which one do you think sounds better?

Thanks for joining CUTGroup! We’ll ask 10 quick questions to complete your signup. Once completed, we’ll send you a $5 VISA gift card!  What is your first name?

or 

Thanks for joining CUTGroup! We’ll ask 10 quick questions to finish your signup. Once completed, we’ll send your $5 gift card! To begin, what’s your first name?

**Comment by smarziano** [comment]
We went with the second option and the SMS Wufoo form has been updated to reflect this. Closing.
