### ISSUE TITLE
Need to save phone number somehow

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#104]
Add "question" to wufoo form to ask for number. Patterns will just save the number in that field instead of asking for it?

**Comment by shua123** [comment]
I added a phone number question/field to end of wufoo form. Patterns fills this out before submitting the form

**Comment by shua123** [comment]
https://github.com/smartchicago/kimball/commit/35a58d4695b6d75eb3d279aa3eea2ab343b22d77

**Comment by smarziano** [comment]
The SMS sign-up Wufoo form asks for a phone number, but this is not being asked to the user (since they are texting and we already know their number). Adding this question allows us to capture the phone number and send to Patterns. 

Closing since this is completed.
