### ISSUE TITLE
Search and filter by preferred contact method

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#107]
This relates to #66 

We need to add the functionality in the search to be able to filter and export by "Preferred Contact Method."

**Comment by shua123** [comment]
Initial version will search for EMAIL or SMS. Both and blank not working. https://github.com/smartchicago/kimball/commit/794db5428fa62f2bab27d651c5c285edfa718e84

**Comment by shua123** [comment]
The easiest might be to bulk change the blank contact method values to "unknown" or something.

**Comment by smarziano** [comment]
Here are a couple of things we need to think about:
- Adding a question on the CUTGroup sign-up form on the website that asks preference of contact method
- Sending an email out to (pre-text message) CUTGroup testers asking them if they prefer to receive text messaging over email. If we do this, I don't want to ask them all to respond, my thinking is that it would default to email preference unless otherwise specified. @shua123 my question to you would be then what makes the most sense to tag these testers? Does it make sense to tag them unknown until after that email campaign goes out and after a given amount of time (week or so) we switch all unknowns to EMAIL

**Comment by smarziano** [comment]
We will add the question on the web Wufoo form about preference once text message test notification has been rolled out.

We will bulk update all "Unknown" CUTGroup testers to EMAIL as preferred method of contact, but will send the email asking their preference.

**Comment by shua123** [comment]
rake script written to bulk update all Unknown CUTGroup testers to EMAIL as preferred contact method with commit https://github.com/smartchicago/kimball/commit/0d466cd03d46917c28f75da0aa1c2ca1d769260a. Tested in staging.

**Comment by smarziano** [comment]
This is completed once pushed live. Closing this issue.
