### ISSUE TITLE
Patterns-Wufoo-Twilio connections and settings

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#112]
User scenario: From Patterns admin, user is able to create an association between a Wufoo form id and keyword. When the keyword is texted to the Twilio number, Patterns reads the questions from the specified Wufoo form and saves the answers to the Wufoo form.

* Create Model to save setting.
  * Possible schema: 
     * id
     * name/description
     * Wufoo form ID

* Create POST endpoint that is built from the Model to respond to incoming Twilio messages

**Comment by shua123** [comment]
Initial version: https://github.com/smartchicago/kimball/commit/724c283ef590b06e149799e9a44e5c11bfbec5fd

At this point there is still an issue with the final message (or messages in the case of signup)

**Comment by shua123** [comment]
Add final message field to model. Signup form final question will still have to be hard coded right now

**Comment by shua123** [comment]
I have added 2 fields to this model. end_message and form_type.

if form_type = "signup", end_message is ignored
Otherwise, end_message is the message that will be sent at the end of the form.

**Comment by smarziano** [comment]
Since we want to send messages from the same number for both sign-up as well as test notification, testers must text a keyword to start the sign-up process. Keywords can be changed or added in the "Twilio-Wufoo Connections" page. Multiple keywords can be included for sign-up (example: "hello," "hi," and "hey" can all work).  

In the future we want to change the usability of this page so it will be easier to distinguish between sign-up and test keyword additions. This relates to #95 when we change to being more test focused.

**Comment by shua123** [comment]
In commit f457af4bd37f138e5165a397f4a4a9b565ea427d the Twilio-Wufoo Connections page now divides up into 3 sections: "Others-Active", "Signup-Active", and Inactive.

**Comment by smarziano** [comment]
@shua123 let's rename the "Others" section to "Tests" because this section will only show active keywords that relate to test text messages such as call-out/availability messages.

**Comment by shua123** [comment]
"Others" renamed to "Tests" in https://github.com/smartchicago/kimball/commit/44d00731578e1f7698ab67949d1efe6fae434692

**Comment by smarziano** [comment]
@shua123 Instead of "Twilio-Wufoo Connections" this page should be renamed "SMS Campaigns" (email sent to testers will be labeled as "Email Campaigns")

**Comment by smarziano** [comment]
Closing this issue because it is completed for text test notification. As we do the future re-design we want to think about how Import Phone Numbers can be part of the SMS campaigns page.
