### ISSUE TITLE
Improve search function to filter/segment

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#114]
This relates to #107, but I also want to filter by responses that are multiple choice questions. Examples:
_What is the device you use the most often to connect to the Internet?_
&
_What is the primary way you connect to the Internet?_

This will need to take in account that we changed forms throughout the last two years from a drop-down menu question to a multiple-choice question. Language might have also been changed in the answer options.

**Comment by shua123** [comment]
Initial version added with commit https://github.com/smartchicago/kimball/commit/28e6ea19e87a98d6634d2334a5a8df220726bd22
for device type and connection type

@smarziano On staging. Right now there is just one device/connection type filter and then it checks both primary and secondary. (This is how the Device Description and Connection Description searches were set up.) I can switch it to only search primary or however you want.

**Comment by shua123** [comment]
I also updated tags to pre-populate list of tags and made it multiselect

**Comment by smarziano** [comment]
Initial thoughts:
- It looks a bit bulky right now because it shows all of the responses instead of having a drop-down menu option.
- It would be good to have an option to let it search for only primary OR both primary and secondary
- I am unable to deselect an option once it has been selected

**Comment by smarziano** [comment]
Regarding bulkiness: I understand that this allows for selecting multiple options. It would be ideal still to have a way to select multiple options from a drop-down. At this time it is sufficient, but @shua123 please keep investigating. I worry specifically about the Tags list getting too long.

Re: deselecting: We figured out the workaround to select Control/Command + Click at this time. Might be good to add to "Search tips"

_Tiers of searching:_
First column should be about the person -- Name, email address, zip code, Tags can also fit here
Second column should be about device type & connection type & preferred contact method
Third column should relate to descriptions

Things that are not as important or frequently searched:
- Verified?
- Form submission content
- Event (this will become less of a priority on the search page when we work on other enhancements, see #95)
- Ward (this is outdated)

**Comment by shua123** [comment]
I have reordered the search options based on the above comment. The not important ones are in a div that starts out hidden. https://github.com/smartchicago/kimball/commit/154681e985b455abeff39e7bdf791d91fe0f0bef

**Comment by smarziano** [comment]
@shua123 _Address_ field can be added to the not frequently searched list. 

Right now we also have "Show advanced search" from the old version, which can be removed. New "Click to Show Additional Options" can be put in that place and renamed to "Show additional options."

**Comment by shua123** [comment]
Make "Show Addtional Options" a button

**Comment by shua123** [comment]
"Show Additional Options" is now a button https://github.com/smartchicago/kimball/commit/342e651c738caba28eedde5c548bdabfecec6ca9

**Comment by smarziano** [comment]
This works for our current needs. Closing issue.
