### ISSUE TITLE
Provide option on search page to send text message to segmented group

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#115]
This relates to #113 & #114 

Currently on the Patterns search page, there is an option to save list as CSV and export it to Mailchimp. The ideal solution would be that we would not have to filter testers who prefer text messages and Patterns would know when to export to Mailchimp and when to send text message. This is a long-term solution.

For the short-term, we need another option to "Send Text Message to list" or "Export list to..." (export if we decided to use another service to manage text messaging).

**Comment by shua123** [comment]
Initial version of this is functional as of commit https://github.com/smartchicago/kimball/commit/a160216823f313e0c1f35a22b2e8beca2fd6d8ca . A form at the bottom of the search page allows user to enter up to 2 messages to send.

**Comment by smarziano** [comment]
This is completed. The longer-term issue of Patterns knowing what message to send to each tester will be addressed a later time.
