### ISSUE TITLE
Add function to import phone numbers (to send text message)

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#117]
Once testers have been segmented and respond to the screening question texts (relates to #115), I will need to look at those testers' responses and make sure they are qualified for the test. Testers who do not qualify will need to receive a text message stating they have not been selected (similar to what we do with emails). Testers who are qualified will then will need to receive another text asking about their availability (this is also when we share location information). 

Current workflow will be that I will use Wufoo to determine qualification for test, and then I will need a function to import the phone numbers for each group (Selected/Not Selected) to Patterns to continue the text message conversation.

**Comment by shua123** [comment]
Initial version of this added in commit https://github.com/smartchicago/kimball/commit/76ad5b3025c452ca996b0382666e38561c1311bb .

User uploads a csv that contains a field name "phone_number", enters up to 2 messages.

**Comment by smarziano** [comment]
@shua123 -- you can add this "Import Phone Numbers" tab under "More" on the nav bar. Otherwise this functionality works and closing issue.
