### ISSUE TITLE
Provide option when text message does not match keyword

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#121]
During sign-up and test call-out SMS, we need to provide a specific path for testers who text back but it does not match the keyword given. The first message should be asking the tester to repeat the keyword since it might have been misspelled. 

If the tester texts back a second time *without* a keyword, we should determine how to handle this message. How do we talk back to this tester? This is very relevant to issue #101.

**Comment by shua123** [comment]
In https://github.com/smartchicago/kimball/commit/342e651c738caba28eedde5c548bdabfecec6ca9 it will say "I did not understand that. Please re-type your message." no matter how many times they try.

**Comment by shua123** [comment]
change to "I did not understand that. Please re-type your keyword"

**Comment by shua123** [comment]
Changed text to keyword in commit https://github.com/smartchicago/kimball/commit/4c88d7c719bec067e901cfc2509b1f3e010af915#diff-e1d34ad5fdc033f274dba592c57e6506

**Comment by smarziano** [comment]
This has been updated, therefore, closing issue. 

In the future, we still want to think about how to help texters better as explained in #101
