### ISSUE TITLE
Convert text messages to GSM before sending

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#130]
Ensure all messages do not have unicode characters before sending.
More at https://www.twilio.com/help/faq/sms/why-are-my-messages-with-unicode-being-split
http://chadselph.github.io/smssplit/

Possible conversion code: https://github.com/livebg/smstools

**Comment by shua123** [comment]
I have implemented a function (at https://github.com/smartchicago/kimball/blob/delayedtext/app/controllers/concerns/gsm_helper.rb) that does a couple things:

1. Replace known "bad" characters with GSM-okay equivalents. This is currently managed through a Hash that could be manually updated in the code. I have started it with some of the ones we have encountered so far:
`map = 
    { 
      "“" => "\"",
      "”" => "\"", 
      "—" => "-" 
    }`
2. Take this "cleaned" message and run it through GSMEncoder.encode, replacing any remaining "bad" characters with a space.

This is making use of the gsm_encoder gem from https://github.com/yury/gsm_encoder.

In commit https://github.com/smartchicago/kimball/commit/3af3831d5a0fd893d30c69e83e81948a1d2755f7

**Comment by shua123** [comment]
Another part of this should be taking a look at the process for the creation of these messages. Are they being copy-pasted from a certain place that produces "bad" characters, etc.

**Comment by shua123** [comment]
I ran this script through the questions for all wufoo forms and did not find any non-GSM characters beyond the 4 already identified ( “ , ” , — , and ’ )

**Comment by smarziano** [comment]
This is great, closing this issue since completed.
