### ISSUE TITLE
On homepage show recent sign-ups and whether or not they received sign-up gift card

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#132]
This relates to #67.

As soon as a user logs in to Patterns, the landing page should show recent testers who have signed up to be part of the CUTGroup. Underneath their name it should show whether or not they have received a gift card.

Here is the wireframe page as an example:
https://moqups.com/smartchicago/W9OgjlHV/p:ac51dcde6

If the tester has not received a gift card there will be two ways to add that information:
1) by clicking on the tester name, you will be directed to their tester profile page where you will be able to add the gift card information directly
2) by clicking on the link labeled "Gift Cards" in the navbar you can bulk upload gift card information for multiple testers

**Comment by shua123** [comment]
Change "Received Gift Card" to "Gift Card Mailed"

**Comment by smarziano** [comment]
This is live. Closing issue!
