### ISSUE TITLE
Add function to bulk add gift card information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#134]
This relates to #67 and #132
See this wireframe page as example: https://moqups.com/smartchicago/W9OgjlHV/p:a4288ea2a

We want to add gift card information for multiple testers at one time. This will be useful for both recent sign-up gift cards or test gift cards where we are adding information for many testers at one time.

**Comment by shua123** [comment]
The Mailed checkbox would be a confirmation for the submission and does not need to be stored in the database.

**Comment by shua123** [comment]
The Test Gift Cards section is mostly filled out before the test/event. After event if the person did not attend the gift card could be removed from the test+person association

**Comment by smarziano** [comment]
This is done for sign-ups. Therefore, I am adding the "Waiting on Merge" label.

We need to think about the full structure of the test/event pages, which will be work that comes later.

**Comment by smarziano** [comment]
For our current needs, this is working well. In the future, we will think more about adding gift cards for tests. I am closing this issue now.
