### ISSUE TITLE
Add way to search for gift cards by last 4 digits

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#135]
A field should be added to the Patterns advanced search page that allows the user to search for a tester by the last four digits of the gift card they received.

<img width="1253" alt="screen shot 2015-12-14 at 5 15 26 pm" src="https://cloud.githubusercontent.com/assets/5550969/11797084/525a63d0-a286-11e5-8c46-b44a454861a2.png">

**Comment by smarziano** [comment]
Currently, you have to search by the last five digits (issue #180). @shua123 I think you can remove searching by batch ID. I believe I would only search by the last five digits because that will be the information that the CUTGroup tester would give me.

**Comment by shua123** [comment]
Searching by gift card number (last 5 digits) is available on gift card index page and main search page.

**Comment by smarziano** [comment]
@shua123 small error on /search page where "Gift card" is listed twice
<img width="290" alt="screen shot 2016-09-12 at 3 25 48 pm" src="https://cloud.githubusercontent.com/assets/5550969/18451589/3c4fc4ce-78fd-11e6-8340-9ad294d145e0.png">

Otherwise, this is good to go!

**Comment by smarziano** [comment]
This works and is live. Closing issue!
