### ISSUE TITLE
Fix tests to properly check both sms and web form signups

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#148]

**Comment by shua123** [comment]
For Wufoo Submissions, have patterns first try to match on email address and then try phone number if no email address match.

**Comment by smarziano** [comment]
I will also change future form fields from Email type to single text field and allow us to capture either email or phone number.

**Comment by smarziano** [comment]
@shua123 the new field will be a single line text field named "Email or Phone Number"

**Comment by shua123** [comment]
Update submissions model and controller to change form_email to something that looks for new Email or Phone Number field.

**Comment by shua123** [comment]
Types of forms:

Form Type | Response Method | Field Name
---------------|--------------------------|--------------------
Initial Callout | Email Link to web form | "Email"
Initial Callout | SMS form fill | "Phone number"
Availability | Email Link to web form | "Email"
Availability | SMS form fill | "Phone number"
CUTGroup Test | Proctor web form | "Email or Phone Number"

@smarziano Does this cover the combinations of wufoo form submissions? 

The other one I can think of is if we implemented this...
> I just had an idea that even though testers prefer text message, they might be interested in answering questions via their browser.

**Comment by shua123** [comment]
Okay, searching for all 3 versions (case insensitive)

    field_name_options = ['email', 'email or phone number', 'phone number']
    JSON.parse(field_structure)['Fields'].each do |field|
      if field_name_options.include? field['Title'].downcase
        return field_value(field['ID'])
      end
    end
    return nil

https://github.com/smartchicago/kimball/commit/b1b6403dbcaf7381ac32d699e1a64ab9ddfefa06#diff-8b04dfc748ae7c73f82a96d00a3db3c2R63

**Comment by smarziano** [comment]
Closing this is now live.
