### ISSUE TITLE
Page number layout is missing proper styling on staging "People" page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#153]
Based on recent commits to staging with pull request https://github.com/smartchicago/kimball/pull/151
It seems that page numbers on the "People" page is listed vertically vs. horizontally. Here is a screenshot:

<img width="1229" alt="screen shot 2016-02-04 at 3 01 12 pm" src="https://cloud.githubusercontent.com/assets/5550969/12829521/2a52c43e-cb50-11e5-8294-9bf03d8c56ab.png">

It should like how it currently does on the live version of Patterns:

<img width="1180" alt="screen shot 2016-02-04 at 3 02 00 pm" src="https://cloud.githubusercontent.com/assets/5550969/12829536/4d1f57d4-cb50-11e5-9916-5e29f082b372.png">

**Comment by shua123** [comment]
Fixed with commit https://github.com/smartchicago/kimball/commit/04dad234eee524bb1d0cd470e5d41bd3303f0b35
