### ISSUE TITLE
Update ElasticSearch version 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#154]
Currently we are using a very outdated version of ElasticSearch and sometimes search will stop working. We want to update to the most recent of ElasticSearch.

This issue relates to other ElasticSearch issues #72 and #73

**Comment by shua123** [comment]
Experimentation!

We are running ElasticSearch v0.20.6 with the Tire ("retire") gem. 
I installed and tested v2.13.x, v1.7.5, and v0.90.13. With all of them, Elasticsearch did not like the submissions part and would fail indexing for persons with associated submissions.
> MapperParsingException[failed to parse [submissions]]; nested: IllegalArgumentException[unknown property [submission_values]];

So I think we need to switch from Tire to elasticsearch-rails before enabling a new version of elasticsearch.

@cromulus I know you were looking at some search stuff. If you want to tackle replacing Tire before we get a chance to do it feel free to do so.

**Comment by cromulus** [comment]
@shua123 I'm running 2.3.1 on production and now in the vagrant box. I did some updates to the code to cleaned it up a bit.

That said, looking into elasticsearch-rails, the interface isn't all that different. We probably could swap it out fairly easily. 

I haven't had a chance to test the submissions bits. Let me see if I can figure that out.

**Comment by smarziano** [comment]
Making this a high priority item. This is happening too often and is really making test management difficult.

**Comment by smarziano** [comment]
Closing this issue since we switched to ransack.
