### ISSUE TITLE
Add way to add test results manually to a tester

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#155]
This relates closely to issue #119. When a webhook does not work and the form results are not submitted to Patterns in association with a person, there is no way to add these form results manually. It would be ideal to have an easy way to input data from a form to a person's profile.

**Comment by shua123** [comment]
add generic Rails form and way to add data from Wufoo in current Patterns submission format

**Comment by smarziano** [comment]
Add submission function has been added
