### ISSUE TITLE
Create new webhook for CUTGroup Test Wufoo Forms

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#157]
This relates to issue #119. We will create a new webhook for all Wufoo forms that are used for testing sessions. This will help us keep account for the number of tests that testers have participated in which relates to #94.

**Comment by shua123** [comment]
Add submission type to submissions table

**Comment by smarziano** [comment]
Instead of creating a new webhook, we can easily create a hidden field with a predefined value (example: "availability" for availability forms, "test" for test forms) to associate the type of form with the phase of the test (phases being screening, availability, test part 1, part 2, etc) in Patterns. 

http://www.wufoo.com/guides/using-hidden-fields-forms/

**Comment by shua123** [comment]
Steps for this:

1. @smarziano Determine the title/name for what this field will be in Wufoo forms
2. @smarziano Initial list of form types
3. @shua123 Make form_type into enum with initial form types from (2)
4. @shua123 Add function that finds hidden field and assigns correct form_type

**Comment by smarziano** [comment]
My thought is to create a field at the very beginning of each form that is called "Form type." Then I will change the "Show field to" setting it to "Admin Only." In the "Predefined value" field, I add one of three types of form: Screening, Availability, & Test.

![image](https://cloud.githubusercontent.com/assets/5550969/14087001/8edd2716-f4ed-11e5-8624-b78e86d292f3.png)

Some tests have two or more parts, but I still think that they can all be listed as "Test."

**Comment by shua123** [comment]
"Admin Only" fields do not get sent through the API so this is a problem for the SMS versions. Even when setting it with a default value in Wufoo, it ends up being blank for submissions sent through the API from Patterns.

New Idea:

-  For forms that will be filled out on the web, make the field "Admin Only" 
-  For forms that will be filled out through the Twilio->Patterns->Wufoo method:
      1.  Create the field at the end of the form after the phone number field. Make it "Everyone" not "Admin Only." 
      2.  When creating the SMS Campaign in Patterns, the Form Type options will be these choices. https://github.com/smartchicago/kimball/commit/da8ec6c671afe0ddc324e38b6380e6883afbb7fe ![image](https://cloud.githubusercontent.com/assets/1593537/14408203/cf8d5d64-feaf-11e5-99e1-d4b1cc8934c0.png) 
      3.  When Patterns submits the answers from the SMS conversation, it will also submit the Form Type from the SMS Campaign. https://github.com/smartchicago/kimball/commit/a325b8d0383aae6c6962f3204ccb42f88b94c209

**Comment by smarziano** [comment]
This has been completed and merged: a325b8d  Closing issue.
