### ISSUE TITLE
SMS campaigns names are not being captured on tester profile pages

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#165]
This is relevant to issue #127. Currently all communications campaigns are being listed on tester profile pages as "TwilioWufoo" and does not use the SMS campaign name defined.

Here is an example of a communications list being captured on a tester's profile page:
<img width="623" alt="screen shot 2016-03-09 at 12 04 07 pm" src="https://cloud.githubusercontent.com/assets/5550969/13645219/89acdb2c-e5ef-11e5-98ab-cb16ee4b55aa.png">

**Comment by shua123** [comment]
Names are now displaying properly. 

To Do:

- [ ] Dedupe messages so that only one instance of campaign is shown.

**Comment by shua123** [comment]
Fixed with https://github.com/smartchicago/kimball/commit/de70a275335247c110c76e3c81d81b9698f523c5
