### ISSUE TITLE
"Forgot Password" is broken on staging

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#171]
On staging, whenever I try to reset my password I get this error after putting my email in and clicking on the "Send me reset instructions" button:

<img width="635" alt="screen shot 2016-04-05 at 4 09 13 pm" src="https://cloud.githubusercontent.com/assets/5550969/14298150/df51c222-fb48-11e5-985f-d6524f67d310.png">

**Comment by shua123** [comment]
This should be fixed.

**Comment by smarziano** [comment]
@shua123 I get that error message above when trying to get to the staging site now.

**Comment by shua123** [comment]
now it should be fixed...

**Comment by smarziano** [comment]
I am now getting this error when trying to enter a new password:
<img width="514" alt="screen shot 2016-04-18 at 1 07 51 pm" src="https://cloud.githubusercontent.com/assets/5550969/14615593/05dfda6e-056c-11e6-9c15-63cbfee35b40.png">
