### ISSUE TITLE
Update error message when duplicate gift card number is entered

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#177]
When a gift card number has been added that is already in the system this error message appears:
<img width="444" alt="screen shot 2016-07-25 at 10 11 08 am" src="https://cloud.githubusercontent.com/assets/5550969/17106221/2ec48ed0-5250-11e6-840a-1a7a9211e4db.png">

This task is to update the language in this message.

**Comment by shua123** [comment]
https://github.com/smartchicago/kimball/commit/08fbeca20028fb33adf2c41d6b746fb8d0e06037

**Comment by smarziano** [comment]
This is updated on staging, my only thoughts are to make it more prominent. Either a dialog box or clearer text underneath the gift card line to show that there is an error and why.

**Comment by smarziano** [comment]
I still think we can make the error message more prominent, but I understand that it might not be needed at this time. I am going to use it and determine if there is real need for this. I am going to close this issue for now.
