### ISSUE TITLE
Add way to export sign-up gift card information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#178]
I would like to export the gift card information to an excel document so that we can create a back-up file. 

I imagine exporting sign-up gift cards would exclude test gift cards.

**Comment by shua123** [comment]
Would this be a raw gift card table dump? Would you want some associated person information part of this (name, address?)?

**Comment by smarziano** [comment]
@shua123 I expect to export gift card number, expiration date, corresponding gift card info (sign-up, test, etc), first and last name, address, phone number and email.

**Comment by shua123** [comment]
- [ ] Display reason text instead of number
- [ ] Add associated person's info (first and last name, address, phone number and email.)

**Comment by shua123** [comment]
- [ ] Add person id and gift card creation date

**Comment by shua123** [comment]
- [ ] Have csv export match filtered search

**Comment by shua123** [comment]
Switched to ransack for gift card search and made sure csv properly filters. https://github.com/smartchicago/kimball/commit/e90eca974033979477b00d268f60ca55808e5b69

**Comment by smarziano** [comment]
All associated tasks are done. Adding "Waiting on Merge" label.

**Comment by smarziano** [comment]
This is live. Closing issue.
