### ISSUE TITLE
Change format of gift card number to include spaces between groupings

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#180]
Currently on staging, the card number is one long string, and it would be much easier to add the gift card numbers if they were grouped in fours. 

Therefore, I would like to see a space between every 4 numbers in this field:
<img width="244" alt="screen shot 2016-07-25 at 10 34 40 am" src="https://cloud.githubusercontent.com/assets/5550969/17107095/6c3c8c7e-5253-11e6-8b39-33e7347955a7.png">

**Comment by cromulus** [comment]
IMHO we really really don't want to store full gift card numbers.

If we are hacked, the money on them will be taken.

Type + Last 4 digits should be enough to uniquely identify them.

**Comment by smarziano** [comment]
@cromulus We are going to follow-up with our team about security across the board. I am not as concerned about the money as I am with losing personal info. 

@shua123 Let's move forward with a Batch ID and then last 5 digits of the gift card.

**Comment by smarziano** [comment]
Now on staging via commit https://github.com/smartchicago/kimball/commit/3025b1c2883a22735e92fb4002265ff4711f47f8 we are only capturing the last five digits. I think it would be good to change the formatting of this field to make it clearer to other users what numbers we are capturing. So in the field showing something like 
<img width="237" alt="screen shot 2016-08-15 at 2 40 57 pm" src="https://cloud.githubusercontent.com/assets/5550969/17676962/5000f0c8-62f6-11e6-97b1-552e07dbc1ec.png">

**Comment by smarziano** [comment]
I really appreciate the update to formatting for gift cards in commit https://github.com/smartchicago/kimball/commit/c5c5404e9a8e6e791d08cf7bea113da8e3edcf90

I think this is going to be much easier to read moving forward. Adding waiting on merge label.

**Comment by smarziano** [comment]
This is now live. Closing issue.
