### ISSUE TITLE
Remove "Import Phone Numbers" from nav bar

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#182]
Since "Gift Cards" has been added to nav bar, it's getting pretty busy. I think it makes more sense  to add a button to this page on the "SMS Campaigns" page or if that doesn't work adding it as an option under "More."

**Comment by shua123** [comment]
https://github.com/smartchicago/kimball/commit/e51e6a13354d34c3a5ff5951e545de225d9416aa

**Comment by smarziano** [comment]
This has been updated. Closing issue.
