### ISSUE TITLE
Show total amount earned by tester

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#184]
We would like to add and show the total amount that has been earned by a tester through all sign-up, test, and refer-a-friend gift cards.

As a reference: https://moqups.com/smartchicago/W9OgjlHV/p:aa2aff631

**Comment by shua123** [comment]
- [ ] Have sum update when gift card is added on page

**Comment by smarziano** [comment]
This works on staging. Adding "waiting on merge" label.

**Comment by smarziano** [comment]
This is now live. Closing this issue.
