### ISSUE TITLE
Error opening SMS preferred tester profile page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#189]
When trying to open CUTGroup tester profile pages who are SMS preferred, I receive the following error message:
<img width="1266" alt="screen shot 2016-08-08 at 11 28 22 am" src="https://cloud.githubusercontent.com/assets/5550969/17488169/ba5c519a-5d5d-11e6-8e6d-8ea09dd7fd5e.png">

 A couple of examples of people IDs where I face this problem include 3077, 3085, 3322. I can search and find the record, but I cannot open up the actual profile page.

**Comment by shua123** [comment]
The original version of this code was failing if there wasn't a wufoo form id associated with a text message. The updated version allows this.

**Comment by smarziano** [comment]
Confirmed that this is fixed. Closing!
