### ISSUE TITLE
Error trying to search

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#191]
I tried to search twice first using a name in the nav bar and received the error message below. Then I tried to click "search" to get to the advanced search page to search that way and also received the same error message.

<img width="749" alt="screen shot 2016-08-09 at 7 32 01 pm" src="https://cloud.githubusercontent.com/assets/5550969/17538129/471428b4-5e68-11e6-9fbc-d2232ae568a2.png">

**Comment by shua123** [comment]
restarted elastic search so it should work now

**Comment by smarziano** [comment]
This relates to issue #154 and we need to find a new solution soon. This bug is fixed and closing issue.
