### ISSUE TITLE
Some tags are not pre-populating

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#194]
When I add a tag to a person's profile page, some of the tags will pre-populate. For example, "unsubscribe" will appear in the drop-down menu:
<img width="327" alt="screen shot 2016-08-22 at 10 04 38 pm" src="https://cloud.githubusercontent.com/assets/5550969/17879151/068e5d12-68b5-11e6-99b1-3738ca3a50c4.png">

However, the recent tag I added labeled "Not Cook County" will not pre-populate:
<img width="280" alt="screen shot 2016-08-22 at 10 04 30 pm" src="https://cloud.githubusercontent.com/assets/5550969/17879158/13db8c38-68b5-11e6-8014-74acfedcac5d.png">

This functionality should remain consistent with all tags that we add so that when you type the list of potential tags appear.

**Comment by cromulus** [comment]
This is turbo links breaking stuff

**Comment by smarziano** [comment]
This seems to be working now on production. I am not sure why it wasn't working before and what fixed it now.

<img width="279" alt="screen shot 2016-08-29 at 3 45 03 pm" src="https://cloud.githubusercontent.com/assets/5550969/18066808/9909ed06-6dff-11e6-83d4-ebb36bb0df6a.png">
