### ISSUE TITLE
Add error when there isn't a batch ID

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#197]
On staging, if you add a gift card without a batch ID, the gift card is saved, but the display on the /gift_cards page is broken. All of the fields are moved over one field as can be seen in this screenshot:
<img width="1211" alt="screen shot 2016-09-12 at 3 04 36 pm" src="https://cloud.githubusercontent.com/assets/5550969/18450904/880ab6b0-78fa-11e6-89eb-f744ebe5e35f.png">

All gift cards should have an associated Batch ID. Therefore, there should be an error message if no Batch ID is inputted. (Related to #177)

**Comment by shua123** [comment]
Added validating presence of batch id with https://github.com/smartchicago/kimball/commit/3692f0e9a20dc4f622e9b9cf3bcb43ca063c3048

**Comment by smarziano** [comment]
This is live. Closing issue.
