### ISSUE TITLE
Update display of gift cards on Person page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#198]
I'm looking to save some space on this page and remove some of the links that I won't need. 
<img width="1226" alt="screen shot 2016-09-12 at 3 21 03 pm" src="https://cloud.githubusercontent.com/assets/5550969/18451447/96482fa8-78fc-11e6-91b7-f0b19aa5ca5a.png">

- [x] Remove Gift Card ID column
- [x] Remove "Show" link to record

**Comment by shua123** [comment]
I also removed person id and name since its already on the person's page.

**Comment by smarziano** [comment]
This looks good and is currently live. Closing this issue.
