### ISSUE TITLE
bad link on profile page

### ISSUE THREAD

**Issue by cgansen** [smartchicago/kimball#27]
![](http://dl.dropbox.com/u/19098/Screenshots/24q1.png)

**Comment by smarziano** [comment]
This relates to empty form fields. On the CUTGroup signup forms, we have some fields that are optional, and when a tester does not fill it out, we receive this error. It would better to leave this field blank.

**Comment by shua123** [comment]
This should be fixed with commit https://github.com/smartchicago/kimball/commit/f457af4bd37f138e5165a397f4a4a9b565ea427d
