### ISSUE TITLE
Troubleshoot integration error

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/kimball#50]
We created a new CUTGroup opportunity today. 

The [email announcing this test](http://us5.campaign-archive2.com/?u=085247dea37361c266002462c&id=63604c0cf7) contains a [form](https://smartchicago2012.wufoo.com/forms/cutgroup-test-food-inspection-website/) to qualify the users. 

We're getting lots of signups and it appears that [all of the forms are populating into our system just fine](https://patterns.smartchicagoapps.org/submissions), but we're getting periodically getting this error:  

Your post integration has failed for form "CUTGroup Test: Food Inspection Website".
Error Code: 400
Error Text: (400)
To read more about this type of error, view the [WebHook Error Documentation](http://help.wufoo.com/articles/en_US/SurveyMonkeyArticleType/Integration-Errors).
To stop viewing this message, return to [your integration setup](https://smartchicago2012.wufoo.com/notifications/cutgroup-test-food-inspection-website/), view your errors, and make the suggested corrections.

We've had 17 signups but just 2 errors, if that is helpful...

**Comment by smarziano** [comment]
Closing this issue because this seems to have been solved for the most part. We see this error when testers type in a different email address than the one predefined in the Wufoo form or during tests when a tester adds a different email address.
