### ISSUE TITLE
Pre-populate the user's email address in form submissions

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/kimball#51]
When a user completes a wufoo form indicating their availability, the form is [imported into Patterns](https://patterns.smartchicagoapps.org/submissions) and the entry is appended to the user's record.

In order for this to work, the user has to supply the email address they used when they signed up for the CUTGroup.

In order to reduce user error (or simply providing a separate valid email address), we should pre-populate the user's email address in the form.

See email for example.

This is related to #50 and, in fact, supersedes it.

**Comment by smarziano** [comment]
This has been solved by using Wufoo's API to determine the email field to be filled out and then defining it using the merge field in Mailchimp. Example:
https://smartchicago2012.wufoo.com/forms/cutgroup-test-cook-county-wireframes/def/Field113=*|EMAIL|*

Use & symbol to define and fill in multiple field types on one form.
