### ISSUE TITLE
Documentation fodder

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/kimball#56]
I changed the text of the thank you email, which was still linking people to the food inspection test. Add this to the list of things to be customized when making a new form.

It is under "Form settings" / "Customize Confirmation Email"

Here's the new text:

Thanks for signing up to be a part of the CUT Group! 

We'll let you know when there's an opportunity to do some tests. We expect to announce a remote testing opportunity about on a community mapping editor soon. Email me back if you have any questions!

I am also changing it on the regular signup form

AND:

I unchecked the "public" box for both of the food inspection test forms.

**Comment by smarziano** [comment]
This has been incorporated into current CUTGroup operations, and therefore, closing this issue.
