### ISSUE TITLE
Export to Mailchimp not functioning

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#61]
I am unable to export a list from Patterns to Mailchimp.

Process is: (1) search for an event, (2) choose "Export this list to Mailchimp," (3) name list, (4) click "Export." 

I receive confirmation of export, but the segment cannot be found in Mailchimp (see below).

![screen shot 2015-01-11 at 5 05 17 pm](https://cloud.githubusercontent.com/assets/5550969/5697461/d0ceb150-99b6-11e4-8bf6-ebc1d08872b1.png)

![screen shot 2015-01-11 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/5550969/5697466/f91643ee-99b6-11e4-95b4-26c7b559a12c.png)

**Comment by shua123** [comment]
According to the production log there is an issue with the API key:
> F, [2015-04-13T20:44:11.791980 #18360] FATAL -- : [MailchimpExport#send_to_mailchimp] mce_id: 35 fatal error exporting to Mailchimp: MailChimp API Error: API Key Disabled: ee75320ecd03b9150f939711e5b1560f-us5 (code 104)

**Comment by shua123** [comment]
I think this was fixed when we updated the API key. Can you please check @smarziano ?

**Comment by smarziano** [comment]
Verified that this is working now.
