### ISSUE TITLE
Remove/change ward info for non-Chicago

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#63]
Need to change or remove the ward signup question for outside Chicago.

**Comment by smarziano** [comment]
We will remove the ward signup question, but we will still find ward information using Tribune Boundaries API from the address given. 
http://boundaries.tribapps.com/api/

**Comment by shua123** [comment]
Signup question is removed. At commit https://github.com/smartchicago/kimball/commit/d660a8e1a2482386146e2b4bc7e55486507f7018 ward info is left blank until Geocoding & Boundaries API functionality is added.

**Comment by smarziano** [comment]
Tasks related to Geocoding tester addresses include:
- [ ] Find tool to discover coordinates for tester addresses. This tool will be connected to Patterns. Therefore, CUTGroup tester signs up and address info is sent to Patterns. Patterns then sends address info to this tool, and receives coordinates which is then fed back into Patterns
- [ ] Create coordinates field in tester profile
- [ ] Use http://boundaries.tribapps.com/api/ to feed in coordinates and discover ward (in case of Chicago resident) and municipality (in case of Cook County resident). This information will then be stored in Patterns under Geography ID
- [ ] Change Geography ID to not online include integers (in case of Chicago resident) but also include text to represent municipalities (in case of Cook County resident) 
- [ ] Then we need to create a way for this information to feed onto the map on http://www.cutgroup.org/
- [ ] Create a way to easily filter testers by municipality/ward within Patterns

**Comment by shua123** [comment]
Possibly use geocoder gem https://github.com/alexreisner/geocoder http://www.rubygeocoder.com/

**Comment by smarziano** [comment]
Closing this issue because I have created multiple issues for each piece of the work in this milestone: https://github.com/smartchicago/kimball/milestones/Geocoding%20Testers'%20Addresses
