### ISSUE TITLE
Add preferred contact method to Person schema?

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#66]
Needed to know who to contact via mailchimp and who to contact via twilio-SMS

**Comment by smarziano** [comment]
As part of scope to include CUTGroup texting sign-up/notification, we will add a question so testers can choose how they want to be contacted (via email/text). This will be in the text message conversation that we send as well as the CUTGroup form. In Patterns, we will add a new field in the profile and then make sure it is connected in Mailchimp. This will allow me to quickly segment out the text message preferred testers but still have their emails for other CUTGroup correspondence outside of tests. 

I need to still consider whether or not I want current CUTGroup members to be tagged as email preferred or if it will make sense to ask them their preference either at tests or via email campaign.

**Comment by shua123** [comment]
preferred_contact_method field added to People schema on Development in commit https://github.com/smartchicago/kimball/commit/c732a55d4894e336ab6781331968d61d6d3b6ca2

**Comment by smarziano** [comment]
Closing since this is on development. More work relates to #107
