### ISSUE TITLE
Create model to store gift card information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#67]
In Patterns, we want to associate gift cards with a tester's profile. Here are a few parts of incorporating this into the current system:

_Add a field(s) in a tester profile to add gift cards_
- Initial $5 sign up gift card
- $20 gift cards given for completing tests
- Refer a friend gift cards (which can be either multiple $5 gift cards or a single $20 gift card)

Gift card fields should include the full card number, the expiration date, and the batch number.

_Show signups that need gift cards sent on the homepage_
- Currently on the homepage, we show recent signups. It would be ideal to show new CUTGroup members that need their $5 gift card. 
- Also, we want to export the list of members who need their $5 gift card to excel to make mailing labels for large batches of new signups.

_Search function_
- Incorporate the ability to search tester profiled by the last 4 digits of the gift card.

**Comment by smarziano** [comment]
The process of sending a $5 gift cards includes these steps:
- Export spreadsheet from Wufoo
- Copy and paste new entries into master gift card list (remove fields to match - I don't look at everything)
- Verify if this a new person or if tester has signed up before by checking name, address (partial), email, and phone number (only if there are questions/concerns)

Once verified that it is new, add gift card number and expiration date to master list. If duplicate, write "DUPLICATE" in the gift card number field.

**Comment by shua123** [comment]
Change to store full gift card number not just last four digits

**Comment by smarziano** [comment]
@cromulus - What is Proxy ID for gift cards?

We are going to use the Batch ID field to connect the gift cards to a particular batch number. We are thinking of removing Proxy ID, but wanted to see what your use case is.

**Comment by smarziano** [comment]
Created issue #205, but otherwise, the work here has been completed and we can close this issue.
