### ISSUE TITLE
Monitor & notify for ElasticSearch downtime

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#73]
ElasticSearch is needed for Patterns searching and for saving new people. If the ElasticSearch service stops running, Patterns will not stop saving new sign ups.

**Comment by shua123** [comment]
Some candidates:
http://www.cyberciti.biz/tips/howto-monitor-and-restart-linux-unix-service.html
http://upstart.ubuntu.com/cookbook/#respawn

**Comment by smarziano** [comment]
Closing this issue because we updated to ransack search.
