### ISSUE TITLE
Create sign up verification through Twilio

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#81]
Wufoo sign up form sends to Patterns which sends text message to person to verify/confirm registration. When verified, update verified field in Patterns.

**Comment by smarziano** [comment]
Text message language for verification:

"Thank you for signing up for the CUTGroup! Please text us 'Hello' or 12345 to complete your signup. If you did not sign up, text 'Remove Me' to be removed."

If an incorrect text is made, the language should be:
"Sorry, please try again. Text 'Hello' or 12345 to complete your signup!"

If they are completing signup, language should be:
"Thank you for verifying your account. We will mail you your $5 VISA gift card right away."

If they want to be removed:
"We are sorry for bothering you. You have been removed from the CUTGroup."

**Comment by shua123** [comment]
Implemented with commit https://github.com/smartchicago/kimball/commit/d660a8e1a2482386146e2b4bc7e55486507f7018
