### ISSUE TITLE
Add functionality to have Patterns send new verified people to Mailchimp

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#82]

**Comment by shua123** [comment]
This is done with commit https://github.com/smartchicago/kimball/commit/d660a8e1a2482386146e2b4bc7e55486507f7018 for Twilio verification but not for manual/other verification.

**Comment by shua123** [comment]
Manual verification was added as part of commit https://github.com/smartchicago/kimball/commit/b13f2f8f4d66687e1cd3a3e4bdb472e01106790f. When a user edits a person, the changes will be sent to Mailchimp if the verified field starts with "Verified"

**Comment by smarziano** [comment]
Closing this issue.
