### ISSUE TITLE
Add Mailchimp profile/unsubscribe updates --> Patterns

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#83]
Set up webhook or api sync so that unsubscribes or other changes in Mailchimp are propagated back to Patterns.

**Comment by smarziano** [comment]
The first task is to take the list of email addresses who have unsubscribed or have been cleaned by Mailchimp (cleaned meaning emails have bounced or were undelivered) and tag them correctly in patterns.

I will send a list to @shua123 via email.

**Comment by shua123** [comment]
Investigate: https://apidocs.mailchimp.com/api/how-to/sync-mailchimp-to-you.php

**Comment by shua123** [comment]
I am going to try upgrading the gibbon gem to the newest to take advantage of Mailchimp API 3.0 for updates.

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/

**Comment by smarziano** [comment]
On staging, when testers unsubscribe in Mailchimp, their Patterns' profiles are getting updated. We are tagging testers with an "unsubscribed" tag and adding an automatic note. We also currently have a log to keep track of this change. 

In the future, we might implement automatic updates when testers update their Mailchimp profile but we don't see this as a widely used feature at this time. 

@shua123 please push live when you're ready.

**Comment by shua123** [comment]
When we push the code live, we need to create the webhook in Mailchimp that will send the changes to Patterns.

**Comment by smarziano** [comment]
This is done. Closing!
