### ISSUE TITLE
Wufoo webhook to Patterns is intermittently timing out

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#84]
I think this is related to elasticsearch.Investigating...

**Comment by smarziano** [comment]
I am going to see which Wufoo entries were not submitted to Patterns and provide information about the last missed entry as well as if any patterns come up. 

@shua123 believes this might have resolved itself when the ElasticSearch issue was fixed. ( #73 )

**Comment by smarziano** [comment]
This has not been a problem recently, so closing this issue.
