### ISSUE TITLE
Device type Ids are sent to Mailchimp with their numerical code not text description

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#89]

**Comment by smarziano** [comment]
This appeared to start happening on August 5, 2015. All previous entries seemed to have been sent to Mailchimp correctly.

@shua123 will investigate further about changes made around that time.

**Comment by shua123** [comment]
A fix for this was added as part of commit https://github.com/smartchicago/kimball/commit/b13f2f8f4d66687e1cd3a3e4bdb472e01106790f

**Comment by smarziano** [comment]
Closing this issue.

Adding this note: When a Patterns profile has been updated these changes will now automatically be pushed to Mailchimp. (This is good stuff.)
