### ISSUE TITLE
What is going on with these 0's for connection method?

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#91]
This might be a bug. I need to investigate more.

![image](https://cloud.githubusercontent.com/assets/1593537/8730308/9fa710ea-2bb5-11e5-8f61-62c761f0b590.png)

**Comment by smarziano** [comment]
This is a bug because when looking at the entries within Wufoo, these fields are filled out.
We did make a change from a drop-down menu to a multiple choice option within Wufoo. Not sure if that is the reason for this error.

**Comment by shua123** [comment]
This has been addressed with commit https://github.com/smartchicago/kimball/commit/f457af4bd37f138e5165a397f4a4a9b565ea427d#diff-b1057a1ab43df8a84628e78393e04113

**Comment by smarziano** [comment]
Closing this issue.
