### ISSUE TITLE
Validate SMS wufoo responses

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#99]
This relates to #93 

- [x] Check for valid email address or "SKIP" in email address field. If not a valid email, send this message: "Oops, it looks like that isn't a valid email address. Please try again or text "SKIP" to skip adding an email."
- [x] Check for letters for multiple choice questions. If not a letter, send this message: "Please type only the letter of your answer. Thank you!"
- [x] For multiple choice questions, connect them to proper answer in patterns to remain consistent with online entries.

**Comment by shua123** [comment]
https://github.com/smartchicago/kimball/commit/a237abdd6962030072e2b399edc83af525d07b76 and https://github.com/smartchicago/kimball/commit/294b29790ec0a5148bafc24d27dd863c95f9290c

**Comment by smarziano** [comment]
For multiple choice questions, we should try to limit the letters they can respond with to the options in the questions. Therefore, they can only respond with the letters A, B, C, D

In addition, if the user makes the same mistake twice, can we see about moving on to the next question? This way we try to get clean answers, but we don't get them stuck or frustrated if there are difficulties.

**Comment by shua123** [comment]
"For multiple choice questions, we should try to limit the letters they can respond with to the options in the questions. Therefore, they can only respond with the letters A, B, C, D" - This is now implemented on staging

**Comment by shua123** [comment]
"In addition, if the user makes the same mistake twice, can we see about moving on to the next question? This way we try to get clean answers, but we don't get them stuck or frustrated if there are difficulties."
Added with https://github.com/smartchicago/kimball/commit/46607592272cc7cb96276281c0e64ef9a4526ab8 and https://github.com/smartchicago/kimball/commit/092820307ba8f06fbde4b0673f178f7323c64ab5

**Comment by shua123** [comment]
Implemented with commits mentioned above.
